name: My Jekyll Website
timezone: Europe/London
title: Cyber Security - Dipo Rodipe
url: https://diporodipe.me
description: A personal website featuring Cyber Security, Computer Science and all manner of tech or fun-filled content!

formspree_form_id: meqboywe